In [8]:
# Numpy is space efficient and used in backend of  pandas and plootiing in matplotlib 

In [3]:
import numpy as np

# The Basics

In [57]:
a = np.array([1,2,3], dtype = 'int16') # default datatype due to int16 it only takes 2bytes 
print(a)

[1 2 3]


In [52]:
b = np.array([[1.0,2,3],[4,5,6]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [54]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [15]:
# Get Dimension
a.ndim

1

In [16]:
# Get Dimension
b.ndim

2

In [18]:
# Get shape -- here it gives row commaa columns
a.shape

(3,)

In [19]:
b.shape

(2, 3)

In [27]:
# Get type
a.dtype

dtype('int16')

In [39]:
# Get size --- in bytes of each element
a.itemsize

2

In [55]:
b.itemsize

8

In [56]:
c.itemsize

4

In [48]:
# Get size -- give total elements
a.size



3

In [49]:
b.size

6

In [44]:
# Get Total Size -- give size of array including elemenet size
a.size * a.itemsize

6

In [45]:
# Get total size --- give total size of array including element Size / Aliter
a.nbytes

6

 # Acessing/Changing specific elemens ,rows, Columns etc

In [3]:
import numpy as np

In [36]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [34]:
# Get a specific element [row,column]
a[1, 5]  # it is just like list slicing

13

In [13]:
b = np.array([1,2,3,4])
print(b)

[1 2 3 4]


In [17]:
# Get a specific element [index]
b[1]

2

In [25]:
# Get a specific row
a[0, : ]   # zero row then : mean full array of row zero

array([1, 2, 3, 4, 5, 6, 7])

In [43]:
# Get a specific column  : mean all row and get 1st column elements
a[: , 1]

array([2, 9])

In [37]:
# Getting a little fancy [startindex:endindex:stepsize]
a[0, 1:6:2] # for 0th row 

array([2, 4, 6])

In [38]:
a[0, 1:-1:2]

array([2, 4, 6])

In [40]:
a[1,5] = 20
print(a)
a[:,2] = 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [41]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


## 3d array

In [2]:
import numpy as np

In [3]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [1]:
# Get specific element (work outside in)
b[0,1,1]

NameError: name 'b' is not defined

In [8]:
b[:,1,1] # : mean all

array([4, 8])

In [9]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [15]:
b[:,1,:] = [[1,2],[9,0]]

In [17]:
print(b)

[[[1 2]
  [1 2]]

 [[5 6]
  [9 0]]]


# Initializing Different Types of Arrays

In [24]:
# All 0s matrix
np.zeros(5)  # 1d array of 5 zeros

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros((2,3)) # 2d matrix of 2X3 size of zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [27]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [28]:
# All 1s Matrix
np.ones((4,2,2),dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [31]:
# Any other number 
np.full((2,2),99) # here 2X2 matrix with value 99

array([[99, 99],
       [99, 99]])

In [37]:
# Any other number (full_like)
np.full(a.shape,4)  # it print matrix of size of a with value of each element is 4

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [38]:
# Alither
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [42]:
# Random decimal numbers
np.random.rand(4,2)  # it gives random decimal numbers of size of matrix is 4X2

array([[0.51515506, 0.52849077],
       [0.07635971, 0.25113139],
       [0.6790645 , 0.55338286],
       [0.70941537, 0.2891144 ]])

In [43]:
np.random.rand(4,2,3)

array([[[0.77368571, 0.19235562, 0.58451275],
        [0.95710979, 0.43555987, 0.989571  ]],

       [[0.08439941, 0.36923272, 0.70727794],
        [0.17230033, 0.45052595, 0.29911665]],

       [[0.58095533, 0.40067813, 0.38486619],
        [0.86565576, 0.9592272 , 0.1601438 ]],

       [[0.51725921, 0.76851444, 0.03358193],
        [0.88361588, 0.40425901, 0.8663435 ]]])

In [44]:
np.random.random_sample(a.shape)  # the size of matrix is same as size of matrix a filled with random decimal numbers

array([[0.04023435, 0.93232199, 0.84012744, 0.64129118, 0.61490539,
        0.28126909, 0.42946177],
       [0.02910875, 0.96190579, 0.02697547, 0.43452633, 0.12433196,
        0.28304079, 0.2408409 ]])

In [52]:
# Random integer values
np.random.randint(7)   # it has 7 as upper bound where 0 can be included

1

In [53]:
np.random.randint(7, size=(3,3))  # Matrix of size 3X3 with random numbers between 0(included) to 7(excluded)

array([[1, 5, 5],
       [4, 2, 2],
       [3, 2, 0]])

In [54]:
np.random.randint(4,7, size=(3,3)) # Matrix of size 3X3 with random numbers between 4(included) to 7(excluded)

array([[5, 6, 5],
       [5, 5, 5],
       [4, 5, 6]])

In [56]:
np.random.randint(-4,7, size=(3,3))

array([[-1,  6,  6],
       [ 3,  1,  5],
       [ 6,  2,  0]])

In [58]:
# The identity matrix
np.identity(5) # by default identity matrix is a square matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [72]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 0)  # 3X3 Matrix with axis is zero mean vertical matrix and if 1 mean horizontal matrix
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [75]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays

In [81]:
a = np.array([1,2,3])
b = a   # you see that we change value of b then it will change value of a also because a did'nt go as a copy to b it gives address of a to b
b[0] = 101
print(a)
print(b)

[101   2   3]
[101   2   3]


In [82]:
b = a.copy()
b[1] = 12
print(a)
print(b)

[101   2   3]
[101  12   3]


# Mathematics

In [84]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [86]:
a + 2 # it done for all corresponding elements of array

array([3, 4, 5, 6])

In [88]:
a - 2

array([-1,  0,  1,  2])

In [89]:
a * 2

array([2, 4, 6, 8])

In [90]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [94]:
a % 2  # it make datatype bigger

array([1, 0, 1, 0], dtype=int32)

In [92]:
a += 2
a

array([3, 4, 5, 6])

In [93]:
b = np.array([1,0,1,0])
a + b

array([4, 4, 6, 6])

In [95]:
a ** 2

array([ 9, 16, 25, 36])

In [100]:
# Take the sin 
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

## Linear algebra

In [4]:
import numpy as np

In [15]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

# a*b  This cannot multiply matix
np.matmul(a,b) # This help to multiply matrices

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [11]:
# Find Determinant of a matrix
c = np.identity(3)
np.linalg.det(c)  # linalg = linear algebra and det = determinant

1.0

## Statistics

In [17]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [21]:
# Axis in numpy
# axis = None mean find from all elements 
# axis = 0 mean find from rows of multi dimentional array
# axis = 1 mean find from columns of multi dimentional array

In [26]:
np.min(stats,axis = 1) # it gives minimum column not minimum column value

array([1, 4])

In [27]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [30]:
np.sum(stats, axis = 0) # It adds row 1 with row2 corresponding elements

array([5, 7, 9])

## Reorganizing Arrays

In [39]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)    # it gives shape of array

after = before.reshape((2,2,2)) # reshape previous array
print(after)

(2, 4)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [45]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4]) 
v2 = np.array([5,6,7,8])
# np.vstack([v1,v2])  here we restack array vertically must have same size/shape
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
# Horizointally stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))  # it stack them horizontally must have same rows but have differernt columns 

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous

In [56]:
# Load data from a file
filedata = np.genfromtxt('data.txt',delimiter=',') # by default datatype is float
filedata.astype('int32') # it just make a copy of filedata array not replace it
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [58]:
# To solve this conflict
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

## Boolean masking and Advanced indexing

In [61]:
filedata > 50  # it checks each elemenet which is  greater than 50 or not based on that it print true or false

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [62]:
filedata[filedata > 50] # it gives array of elements where size is greater than 50

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [66]:
# you can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]] # give value at given indices

array([2, 3, 9])

In [68]:
np.any(filedata > 50,axis = 0) #here it takes to compare each row parallel by 50 and if any one value in column is greater than 50 then true

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [69]:
np.all(filedata > 50,axis = 0) #here it takes to compare each row parallel by 50 and if all values in column is greater than 50 then true

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [70]:
np.all(filedata > 50,axis = 1) #here it takes to compare each column by 50 and if all values in row is greater than 50 then true

array([False, False, False])

In [72]:
np.any(filedata > 50,axis = 1) #here it takes to compare each column by 50 and if any values in row is greater than 50 then true

array([ True,  True,  True])

In [77]:
(~(filedata > 50) & (filedata <100)) # Give all values as true which lie between 50 to 100 and ~ mean not

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])